### ISSUE TITLE
Allow the path of "babushka-deps" to be specified on the command line.

### ISSUE THREAD

**Issue by philc** [benhoskings/babushka#197]
During a deploy, I'd like to run babushka from the root of my project repo (so file path references can all be uniform -- from the root) but this requires me to have a babushka-deps folder created at the top level of my project. It would be nice if I could stash babushka-deps into a subfolder (e.g. "deploy/babushka-deps") with the rest of my deploy artifacts.

**Comment by benhoskings** [comment]
Moving this to the TODO list.
