### ISSUE TITLE
Changing templated file after parameter changes

### ISSUE THREAD

**Issue by ashak** [benhoskings/babushka#246]
I have a fairly simple dep:
    dep 'openvpn etc default openvpn', :server do
      met? {
        Babushka::Renderable.new("/etc/default/openvpn").from?(dependency.load_path.parent / "openvpn/etc_default_openvpn.erb")
      }
      meet {
        render_erb "openvpn/etc_default_openvpn.erb", :to => "/etc/default/openvpn"
      }
    end

And a fairly simple template:
    AUTOSTART="<%= server %>"

My dep that I use to wrap all the deps for a particular server contains:
    requires 'openvpn'.with(:server => 'vpn.somedomain.com')

On first run, as i'd expect /etc/default/openvpn gets created and it contains the one line:
    AUTOSTART = "vpn.somedomain.com"

So far so good. I then added some more to the template so. It now contains:
    AUTOSTART="<%= server %>"
    OPTARGS=""

Running babushka again my /etc/default/openvpn file is updated and it now says:
    AUTOSTART="vpn.somedomain.com"
    OPTARGS=""

Again.. so far so good. I then realise that i've used the wrong server name, so I update the dpe wrapping all other deps so it looks like:
    requires 'openvpn'.with(:server => 'somethingelse.somedomain.com')

I run babushka, but I see no suggstion that the /etc/default/openvpn file has been modified?

I look at the file and it still contains vpn.somedomain.com

If I delete /etc/default/openvpn, then run babushka again, it gets created again with the content that I expect.

This seems to me like it's broken. Or i'm misunderstanding something!

**Comment by benhoskings** [comment]
Closing this; added to TODO list for a rainy day.
