### ISSUE TITLE
Support adding local git repositories

### ISSUE THREAD

**Issue by quad** [benhoskings/babushka#251]
At work today, I tried:

```
$ babushka sources --add site /vagrant/babushka-deps/
Nothing to add for site.
$ ls -ald /vagrant/babushka-deps/.git/
drwxr-xr-x 1 vagrant vagrant 442 Jan 31 04:05 /vagrant/babushka-deps/.git/
$ git clone /vagrant/babushka-deps/     
Cloning into 'babushka-deps'...
done.
```

Yes, well.

I propose a change on `cloneable?` [here](https://github.com/benhoskings/babushka/blob/master/lib/babushka/source.rb#L124) in line with the logic already in `cloned?`. In short:

``` ruby
def cloneable?
  return File.directory?(path / '.git') if :local == type
  [:public, :private].include? type
end
```

Which is ugly, if only because I'm afraid of more types than `:public`, `:private`, and `:local`.

Upon further thought, why even check all this stuff? Why not just `git ls-remote` and let `git` tell us if the path/URL is valid? Or just do the clone and see what happens...

**Comment by benhoskings** [comment]
Moving this to the TODO list for a rainy day.
