### ISSUE TITLE
'apt source' dep can't produce sources line for jenkins

### ISSUE THREAD

**Issue by schnittchen** [benhoskings/babushka#287]
Line found here http://pkg.jenkins-ci.org/debian/

```
http://pkg.jenkins-ci.org/debian/ binary/
```

Apt happily accepts it, however I found no way to use the 'apt source' dep to produce it.

Although it's easy to work around this, I'm wondering why this dep needs to be so complex. Why not have

```
requires 'apt source line'.with('http://pkg.jenkins-ci.org/debian/')
```

instead?

**Comment by benhoskings** [comment]
Closing this; feel free to reopen if it's still a problem.
