### ISSUE TITLE
Idea: boolean semantics for parameters

### ISSUE THREAD

**Issue by schnittchen** [benhoskings/babushka#288]
I need parameters with boolean semantics every now and then.

Since possible inputs may include things like 'yes', 'y', 'true', 'n', 'no', too simple checks may cover misinterpretations, and repeating explicit regexp-type checks over my deps is neither DRY nor nice to read.

I suggest adding a yes? method (not sure about the name) on Parameter that returns either true or false and raises an exception when the value is not clear to interpret.

Bonus points would be to extend prompting for this case :)

What do you think, Ben? I would get hacking on this when I find the time.

**Comment by benhoskings** [comment]
Moving this to the TODO list for a rainy day.
