### ISSUE TITLE
Encoding problem in SystemProfile

### ISSUE THREAD

**Issue by schnittchen** [benhoskings/babushka#301]
I'm reporting this from a transcript of the error, so this is probably not 100% exact:

system_profile.rb:176 in []: invalid byte sequence in US-ASCII

Running on Fedora 19, ruby version 2.0.0p353

It's getting the release number from /etc/redhat_release which contains the codename in brackets: Schrödinger's cat.

I'm sure it's not a Heisenbug ;)

**Comment by benhoskings** [comment]
This has since been fixed.
