### ISSUE TITLE
Latest install of hombrew breaks babushka homebrew

### ISSUE THREAD

**Issue by cheister** [benhoskings/babushka#323]
They changed the default Homebrew installer to do a shallow clone by default  https://github.com/Homebrew/install/commit/9a401211698b876a656e68e1494aeb982cc50926

This breaks `babushka hombrew`  which checks for a certain sha in the homebrew git repo https://github.com/benhoskings/babushka/blob/master/deps/homebrew.rb#L19  because the shallow clone does not have any history.

You can get around this by add --full to the homebrew install which will do the full clone.  

I'm not sure how you want to fix the babushka meet clause though.

**Comment by benhoskings** [comment]
Didn't see this issue, sorry - this was fixed in 571eb70.
