### ISSUE TITLE
Improve handling of identity_dirs that shouldn't be descended into during resource extraction

### ISSUE THREAD

**Issue by timriley** [benhoskings/babushka#326]
I'm writing some deps to install LaunchBar actions. These are distributed on the internet as `.lbaction` files that are actually just zip archives. Inside the archive is another single `.lbaction` entry (usually with an identical name), which is actually a directory containing the action's source code and other resources.

My dep uses `Babushka::Resource.extract` to download and extract the zipped `.lbaction` file. However, when I'm inside the `extract` block, I noticed that the `cwd` was _already inside_ the single `.lbaction` directory _within_ the archive. This made it difficult to copy the `.lbaction` directory in a single go.

I looked into the babushka source code and noticed this inside `asset.rb`:

```ruby
    def content_subdir
      identity_dirs.reject {|dir|
        %w[app pkg bundle tmbundle prefPane].map {|i|
          /\.#{i}$/
        }.any? {|dont_descend|
          dir[dont_descend]
        }
      }.first
    end
```

This is clearly intended for the case I'm handling now, where an archive has a single directory inside it that the user would want to work with directly, rather than the contents of that directory.

An easy fix would be for me to add `lbaction` to the end of that array.

I'm wondering whether you might prefer some other way to do this. I can think of a few options:

* Expose a `Babushka::Resource.package_directory_extensions` array (or some similar name) with some sane defaults, but which a user can extend from their own deps.
* Or maybe add an `options` hash argument to the end of `Babushka::Resource.extract` where the user could specify something like `descend_into_identity_dir: false`.

What are your thoughts? I'm happy to build whatever approach you prefer :)

**Comment by benhoskings** [comment]
Hi mate, thanks for the excellent report to refresh my memory :)

I think your suggestion of something like `#extract(:descend => false)` is a good one, and if this issue arises more than once or twice I think it'd be worthwhile to add. But considering this is the first time it's come up, I'd be happy with just adding `lbaction` to the list and leaving it hardcoded. (After all, it already includes `tmbundle`, which is just as arbitrary.)

What do you think?

**Comment by timriley** [comment]
Thanks @benhoskings, I like your thinking – also makes my PR super easy :) Give me a few minutes!
