### ISSUE TITLE
sparkle update - url with spaces

### ISSUE THREAD

**Issue by sragu** [benhoskings/babushka#328]
On sparkle updates few vendors provide resource url unescaped, i.e. Sublime Text

http://www.sublimetext.com/updates/3/stable/appcast_osx.xml

This fails the CURL command under resources.rb, a possible solution would be to escape the url before passing it to download?

URI.escape(url.to_s)

Caveats: If the file url provided by vendor is already escaped, we would double escape the url and fail.

**Comment by benhoskings** [comment]
I think `brew cask` support is a better option for this in '17; added to the TODO list to look at someday.
