### ISSUE TITLE
Debian release not properly detected

### ISSUE THREAD

**Issue by victorklos** [benhoskings/babushka#329]
Currently babs detects the release by looking at `/etc/debian_version`. On my Debian machines this contains the phrase "stretch/sid\n", making the release detection fail (the regexp on the version string is the culprit). Worse even, the runner now asks for the release, after which it even creates a `/etc/apt/sources.list.d/babushka.conf` file.

Detection should be done using `lsb_release -sc`, which simply returns the string "stretch".

**Comment by victorklos** [comment]
While looking at the specs I noticed that `spec/babushka/system_profile_spec.rb` is missing an `on  a Debian 8 box` context.

**Comment by benhoskings** [comment]
Thanks for reporting this. I'll push a fix today.

Which dep were you running when the `sources.list.d` entry was generated? That's really messy failure case and I'd like to fix it.

**Comment by victorklos** [comment]
Thanks for the fix! This dep caused the issue:

```ruby
dep 'core software' do
  requires {
    on :linux, 'build tools'
  }
end
```
