### ISSUE TITLE
Detection of public_ip only correct when running Babushka as root

### ISSUE THREAD

**Issue by victorklos** [benhoskings/babushka#330]
Currently babs uses an ingenious call to `ifconfig` to obtain the `public_ip` of the `Babushka.host`. While this would work for regular users, they need to call `/sbin/ifconfig` as `/sbin` is not in the path.

So, the call to `ifconfig` could be changed into `/sbin/ifconfig` or alternatively a new scheme can be created using the `ip` command like so:

```
ip -4 addr show dev <device_goes_here>
```

Additional benefit of using `ip` is that `ifconfig` may become deprecated soon.

**Comment by benhoskings** [comment]
Closing this for now; if it's still a problem patches are welcome.
