### ISSUE TITLE
Idea: Descriptions for deps

### ISSUE THREAD

**Issue by rapheld** [benhoskings/babushka#331]
We use babushka at work and the list of deps has become quite large. Some of the dep names are also fairly long in an attempt to make their purpose clear when running `babushka list`. It would be handy to display a description along with the dep name in that output.

I am thinking of functionality similar to  `rake -T` with a DSL such as `desc 'Some description'` that is alongside the associated task.

**Comment by rapheld** [comment]
@benhoskings thoughts?

**Comment by benhoskings** [comment]
Sorry for the delay.

I'm not opposed to the idea, but I'd prefer not to use the rake style, since it requires setting state between desc/task calls. How about a 'desc' call within the dep?

**Comment by benhoskings** [comment]
Closing this for now; please re-open if you'd like to look into it again.
