### ISSUE TITLE
Babushka tries to extract cloned git directory

### ISSUE THREAD

**Issue by charles-l** [benhoskings/babushka#334]
``` ruby
dep 'lemonbar', :template => 'src' do
  source "git://github.com/LemonBoy/bar.git"
  provides %[lemonbar]
end
```

When it runs, it clones the directory, then throws an error:

```
/usr/local/babushka/lib/babushka/asset.rb:177: in 'for': Don't know how to extract bar
```

Really liking babushka, though. Keep up the good work :)

**Comment by benhoskings** [comment]
Thanks mate. I had a quick look - the problem is that the 'src' template is expecting an archive as the input, and can't handle a directory. I'll patch it when I have a chance but in the meantime, you could use a github tarball URL instead.

**Comment by charles-l** [comment]
@benhoskings alright, cool. I'll use that workaround for now then. Thanks!
