### ISSUE TITLE
Idea: make babushka use facter gem

### ISSUE THREAD

**Issue by victorklos** [benhoskings/babushka#335]
Issues #329 , #330 , #332 and possibly others all seem to point to an underlying issue: it is difficult to get facts about the running system right.

How about using https://github.com/puppetlabs/facter as a dependency? It is backed by the Puppet project so you can expect it to be kept consistent and relevant for some time to come.

**Comment by benhoskings** [comment]
The system detector is definitely brittle in places - facter would probably do a better job. But by depending on an external library I add another installation requirement (and by the looks of the facter readme, it would mean a compiler was required for all babushka installs on linux). At the end of the day, keeping the codebase small and self-contained is a higher priority.
