### ISSUE TITLE
brew_helper.rb is unable to locate taps or formula properly with latest homebrew

### ISSUE THREAD

**Issue by derektamsen** [benhoskings/babushka#336]
When using the brew helper template babushka is unable to locate formula or taps using brew 0.9.9. The following error message is produced:

```
} ✓ homebrew
    meet {
      There is no formula for 'maven' in /usr/local/Library/Formula or /usr/local/Library/Taps.
    }
    'mvn' is missing.
  } ✗ maven.bin
} ✗ maven
```

It appears the path for homebrew taps and formula has been moved under `/usr/local/Hombrew/Library` instead of `/usr/local/Library`.

**Comment by benhoskings** [comment]
Didn't see this issue, sorry - this was fixed in 571eb708.
