### ISSUE TITLE
Running babushka as normal user fails when trying to add apt sources

### ISSUE THREAD

**Issue by mortenlj** [benhoskings/babushka#339]
When trying to use babushka for the first time on a machine, it errors out trying to add an apt source, because it does not have permissions to access files in `/etc/apt/sources.list.d`. Since installing packages works when running as a normal user, I assume it's supposed to be a supported case. It seems like babushka knows to use sudo when installing packages, so it's weird that it assumes to be root in other cases.

I'm running babushka on [HypriotOS](https://blog.hypriot.com/) (a modified raspian, which is a modified debian). To get a running VM, with ssh-access on localhost:5022, use this command:

    # Download kernel from https://github.com/dhruvvyas90/qemu-rpi-kernel/blob/master/kernel-qemu-4.4.34-jessie
    # Download img from https://blog.hypriot.com/downloads/

    $ qemu-system-arm -kernel kernel-qemu-4.4.34-jessie -cpu arm1176 -m 256 -M versatilepb -no-reboot -append "root=/dev/sda2 panic=1 rootfstype=ext4 rw" -redir tcp:5022::22 -drive file=hypriotos-rpi-v1.1.3.img,format=raw
.

    $ whoami
    pirate
.

    $ ls -l babushka-deps/
    total 4
    -rw-r--r-- 1 pirate pirate 30 Feb 20 22:05 autoupdate.rb
.

    $ cat babushka-deps/autoupdate.rb 
    dep 'unattended-upgrades.bin'
.

    $ babushka 'unattended-upgrades.bin'
    unattended-upgrades.bin {
      'unattended-upgrades' is missing.
      apt {
        package manager {
          'apt-get' runs from /usr/bin.
        } ✓ package manager
        apt source {
          meet {
            Adding jessie from http://http.debian.net/debian...        /usr/local/babushka/lib/fancypath/fancypath.rb:197:in `initialize': Permission denied @ rb_sysopen - /etc/apt/sources.list.d/babushka.list
            Check /usr/local/babushka/deps/apt.rb:27.
          } ✗ apt
          'unattended-upgrades' is missing.
        } ✗ unattended-upgrades.bin
        You can view a more detailed log at '/home/pirate/.babushka/logs/unattended-upgrades.bin'.
.

    $ cat /home/pirate/.babushka/logs/unattended-upgrades.bin
    $ git rev-parse --git-dir
    .git
    $ git rev-parse --short HEAD
    5e897c8
    babushka@5e897c8 | /usr/bin/ruby@2.1.5-p273
    $ git rev-parse --git-dir
    fatal: Not a git repository (or any of the parent directories): .git
    unattended-upgrades.bin {
      $ git rev-parse --git-dir
      fatal: Not a git repository (or any of the parent directories): .git
      $ git rev-parse --git-dir
      fatal: Not a git repository (or any of the parent directories): .git
      $ git rev-parse --git-dir
      fatal: Not a git repository (or any of the parent directories): .git
      $ git rev-parse --git-dir
      fatal: Not a git repository (or any of the parent directories): .git
      (defining unattended-upgrades.bin against bin from /tmp/homeassistant/babushka-deps/autoupdate.rb)
      $ lsb_release -sr
      8.0
      setup not defined.
      'unattended-upgrades' is missing.
      $ git rev-parse --git-dir
      fatal: Not a git repository (or any of the parent directories): .git
      prepare not defined.
      apt {
        (defining apt against Babushka::BaseTemplate from /usr/local/babushka/deps/pkg_managers.rb)
        setup not defined.
        package manager {
          (defining package manager against Babushka::BaseTemplate from /usr/local/babushka/deps/pkg_managers.rb)
          setup not defined.
          'apt-get' runs from /usr/bin.
        } ✓ package manager
        apt source {
          (defining apt source against Babushka::BaseTemplate from /usr/local/babushka/deps/apt.rb)
          setup not defined.
          $ grep -R -h \^deb /etc/apt/sources.list /etc/apt/sources.list.d/
          deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi
          deb https://packagecloud.io/Hypriot/rpi/debian/ jessie main
          deb https://packagecloud.io/Hypriot/Schatzkiste/debian/ jessie main
          deb http://archive.raspberrypi.org/debian/ jessie main
          deb [arch=armhf] https://apt.dockerproject.org/repo raspbian-jessie main
          prepare not defined.
          meet {
            before not defined.
            Adding jessie from http://http.debian.net/debian...        /usr/local/babushka/lib/fancypath/fancypath.rb:197:in `initialize': Permission denied @ rb_sysopen - /etc/apt/sources.list.d/babushka.list
            /usr/local/babushka/lib/fancypath/fancypath.rb:197:in `initialize'
            /usr/local/babushka/lib/fancypath/fancypath.rb:197:in `open'
            /usr/local/babushka/lib/fancypath/fancypath.rb:197:in `open'
            /usr/local/babushka/lib/fancypath/fancypath.rb:197:in `write'
            /usr/local/babushka/lib/fancypath/fancypath.rb:202:in `append'
            /usr/local/babushka/deps/apt.rb:27:in `block (3 levels) in <top (required)>'
            /usr/local/babushka/lib/babushka/helpers/log_helpers.rb:39:in `call'
            /usr/local/babushka/lib/babushka/helpers/log_helpers.rb:39:in `log_block'
            /usr/local/babushka/deps/apt.rb:26:in `block (2 levels) in <top (required)>'
            /usr/local/babushka/lib/babushka/dep_definer.rb:49:in `instance_eval'
            /usr/local/babushka/lib/babushka/dep_definer.rb:49:in `invoke'
            /usr/local/babushka/lib/babushka/dep.rb:374:in `invoke'
            /usr/local/babushka/lib/babushka/dep.rb:346:in `block in run_meet'
            /usr/local/babushka/lib/babushka/helpers/log_helpers.rb:115:in `log'
            /usr/local/babushka/lib/babushka/dep.rb:346:in `run_meet'
            /usr/local/babushka/lib/babushka/dep.rb:339:in `run_meet_stage'
            /usr/local/babushka/lib/babushka/dep.rb:329:in `block in run_met'
            /usr/local/babushka/lib/babushka/git_fs.rb:10:in `call'
            /usr/local/babushka/lib/babushka/git_fs.rb:10:in `snapshotting_with'
            /usr/local/babushka/lib/babushka/dep.rb:328:in `run_met'
            /usr/local/babushka/lib/babushka/dep.rb:318:in `run_met_stage'
            /usr/local/babushka/lib/babushka/dep.rb:298:in `block in process!'
            /usr/local/babushka/lib/babushka/helpers/log_helpers.rb:115:in `log'
            /usr/local/babushka/lib/babushka/dep.rb:289:in `process!'
            /usr/local/babushka/lib/babushka/dep.rb:274:in `block in process_with_caching'
            /usr/local/babushka/lib/babushka/dep_cache.rb:14:in `call'
            /usr/local/babushka/lib/babushka/dep_cache.rb:14:in `read'
            /usr/local/babushka/lib/babushka/dep.rb:271:in `process_with_caching'
            /usr/local/babushka/lib/babushka/dep.rb:216:in `process_as_requirement'
            /usr/local/babushka/lib/babushka/dep.rb:366:in `block in run_requirement'
            /usr/local/babushka/lib/babushka/source_pool.rb:68:in `call'
            /usr/local/babushka/lib/babushka/source_pool.rb:68:in `find_or_suggest'
            /usr/local/babushka/lib/babushka/dep.rb:365:in `run_requirement'
            /usr/local/babushka/lib/babushka/dep.rb:353:in `block in run_requirements'
            /usr/local/babushka/lib/babushka/dep.rb:353:in `each'
            /usr/local/babushka/lib/babushka/dep.rb:353:in `all?'
            /usr/local/babushka/lib/babushka/dep.rb:353:in `run_requirements'
            /usr/local/babushka/lib/babushka/dep.rb:318:in `run_met_stage'
            /usr/local/babushka/lib/babushka/dep.rb:298:in `block in process!'
            /usr/local/babushka/lib/babushka/helpers/log_helpers.rb:115:in `log'
            /usr/local/babushka/lib/babushka/dep.rb:289:in `process!'
            /usr/local/babushka/lib/babushka/dep.rb:274:in `block in process_with_caching'
            /usr/local/babushka/lib/babushka/dep_cache.rb:14:in `call'
            /usr/local/babushka/lib/babushka/dep_cache.rb:14:in `read'
            /usr/local/babushka/lib/babushka/dep.rb:271:in `process_with_caching'
            /usr/local/babushka/lib/babushka/dep.rb:216:in `process_as_requirement'
            /usr/local/babushka/lib/babushka/dep.rb:366:in `block in run_requirement'
            /usr/local/babushka/lib/babushka/source_pool.rb:68:in `call'
            /usr/local/babushka/lib/babushka/source_pool.rb:68:in `find_or_suggest'
            /usr/local/babushka/lib/babushka/dep.rb:365:in `run_requirement'
            /usr/local/babushka/lib/babushka/dep.rb:353:in `block in run_requirements'
            /usr/local/babushka/lib/babushka/dep.rb:353:in `each'
            /usr/local/babushka/lib/babushka/dep.rb:353:in `all?'
            /usr/local/babushka/lib/babushka/dep.rb:353:in `run_requirements'
            /usr/local/babushka/lib/babushka/dep.rb:339:in `run_meet_stage'
            /usr/local/babushka/lib/babushka/dep.rb:329:in `block in run_met'
            /usr/local/babushka/lib/babushka/git_fs.rb:10:in `call'
            /usr/local/babushka/lib/babushka/git_fs.rb:10:in `snapshotting_with'
            /usr/local/babushka/lib/babushka/dep.rb:328:in `run_met'
            /usr/local/babushka/lib/babushka/dep.rb:318:in `run_met_stage'
            /usr/local/babushka/lib/babushka/dep.rb:298:in `block in process!'
            /usr/local/babushka/lib/babushka/helpers/log_helpers.rb:115:in `log'
            /usr/local/babushka/lib/babushka/dep.rb:289:in `process!'
            /usr/local/babushka/lib/babushka/dep.rb:274:in `block in process_with_caching'
            /usr/local/babushka/lib/babushka/dep_cache.rb:14:in `call'
            /usr/local/babushka/lib/babushka/dep_cache.rb:14:in `read'
            /usr/local/babushka/lib/babushka/dep.rb:271:in `process_with_caching'
            /usr/local/babushka/lib/babushka/dep.rb:216:in `process_as_requirement'
            /usr/local/babushka/lib/babushka/dep.rb:203:in `process'
            /usr/local/babushka/lib/babushka/task.rb:33:in `block (2 levels) in process_dep'
            /usr/local/babushka/lib/babushka/task.rb:78:in `with_logging'
            /usr/local/babushka/lib/babushka/task.rb:32:in `block in process_dep'
            /usr/local/babushka/lib/babushka/source_pool.rb:68:in `call'
            /usr/local/babushka/lib/babushka/source_pool.rb:68:in `find_or_suggest'
            /usr/local/babushka/lib/babushka/task.rb:30:in `process_dep'
            /usr/local/babushka/lib/babushka/task.rb:22:in `block in process'
            /usr/local/babushka/lib/babushka/task.rb:22:in `each'
            /usr/local/babushka/lib/babushka/task.rb:22:in `all?'
            /usr/local/babushka/lib/babushka/task.rb:22:in `process'
            /usr/local/babushka/lib/babushka/cmdline.rb:66:in `block in <class:Cmdline>'
            /usr/local/babushka/lib/babushka/cmdline/parser.rb:28:in `call'
            /usr/local/babushka/lib/babushka/cmdline/parser.rb:28:in `run'
            /usr/local/babushka/lib/babushka/base.rb:61:in `run'
            /usr/local/bin/babushka:25:in `<main>'
            Check /usr/local/babushka/deps/apt.rb:27.
          } ✗ apt
          'unattended-upgrades' is missing.
        } ✗ unattended-upgrades.bin
        $ git rev-parse --git-dir
        fatal: Not a git repository (or any of the parent directories): .git
        You can view a more detailed log at '/home/pirate/.babushka/logs/unattended-upgrades.bin'.

**Comment by benhoskings** [comment]
Thanks for the report. Perhaps the real problem is that it shouldn't be adding a source in the first place. Could you try removing the 'apt source' requirement on `/usr/local/babushka/deps/pkg_managers.rb:13` and see what happens?

**Comment by mortenlj** [comment]
The underlying problem was that Raspian wasn't properly detected (hence my PR about that). When the detection was fixed, this problem went away.

On the other hand, I'm wondering when adding a default source would be needed, so I think perhaps the 'apt source' requirement could be removed anyway.

**Comment by benhoskings** [comment]
That makes sense, thanks for clarifying. If you get a chance at some point, could you test it with 'apt source' disabled as above?

**Comment by benhoskings** [comment]
Closing this for now, and adding a note to the TODO about clearing up apt sources.
