### ISSUE TITLE
Installing fails on Cygwin

### ISSUE THREAD

**Issue by ElvenSpellmaker** [benhoskings/babushka#342]
Hey there,

Cygwin is a POSIX environment for Windows which provides many common UNIX tools such as sh/bash, etc.

Currently the detection doesn't detect Cygwin and so babushka install fails.

I have managed to modify a couple of files and get the install to succeed (haven't tried using the tool properly yet, but I'd like to soon) and was wondering if you'd like to add support for this.

Below are my initial findings to get the tool to install under Cygwin.

To `system_definition.rb` I added the following dummy code:
```rb
      :cygwin => {
        :cygwin => {
         'foo' => 'foo'
        }
      }
```
to satisfy the need for a `CODENAME`.

To `system_profile.rb` I copied `LinuxSystemProfile` and named it `CygwinSystemProfile`. (This would need a bit of further work as `ifconfig` isn't in Cygwin, but the direct copy is enough to get the tool installed). I also changed `system_str` to `Cygwin`.

To `system_detector.rb` I added the following code to `detect_using_uname` just after the current case statement:
```rb
      if ShellHelpers.shell('uname -o') === 'Cygwin'
        CygwinSystemProfile
      end
```

The reason for the call out to `uname -o` is that the result of `uname -s` from Cygwin is `CYGWIN_NT-10.0` on my Windows 10 system whereas `uname -o` is always `Cygwin` regardless of OS version.

As a side note, and with regards to Cygwin detection, the `os` gem has the following output:
```
irb(main):001:0> require 'os'
=> true
irb(main):002:0> OS.windows?
=> false
irb(main):003:0> OS.linux?
=> false
irb(main):004:0> OS.cygwin?
=> true
irb(main):005:0> OS.posix?
=> true
```

**Comment by benhoskings** [comment]
G'day, sorry for the delay. I've never looked into supporting Cygwin because I don't use it but I'd be happy to merge a PR as long as it doesn't need too much extra logic of its own.
