### ISSUE TITLE
Running an apt package always asks for "release?" on Ubuntu bionic beaver

### ISSUE THREAD

**Issue by Calamari** [benhoskings/babushka#345]
Hiho.

First: I love babushka. It always helped to setup my working Macbook. Now I am switching to linux and trying to update my deps.

I have the problem that the it always asks me for `release?`, which I believe is the codename for the ubuntu version. But the name is included and filled within the `Babushka.host.version_info` as `bionic`. Entering it, will break and I'll have to call the install via sudo. (I guess I hava to call the dep with `sudo: true`.

But why does it always ask for that? Would a simple `apt-get install` not suffice?

**Comment by benhoskings** [comment]
G'day, and thanks. It sounds like https://github.com/benhoskings/babushka/pull/344 will fix your issue?
